/* gateway_main.c — STM32L476RG Gateway Application
 *
 * Packet format (10 bytes, matches ESP32 sender):
 *  [0]   NODE_ID        uint8
 *  [1-2] SEQ            uint16 big-endian
 *  [3-4] TEMP * 10      int16  big-endian   (e.g. 253 = 25.3°C)
 *  [5-6] HUM  * 10      uint16 big-endian
 *  [7-8] VBAT_mV        uint16 big-endian
 *  [9]   CRC-8 (Dallas) over bytes 0..8
 *
 * SPI2: PB13=SCK  PB14=MISO  PB15=MOSI
 * NSS  → PB12    RST → PC6    DIO0 → PC7
 * UART2 (PA2/PA3) 115200 → USB-Serial debug
 *************************************************************/

#include "main.h"
#include "lora_sx1278.h"
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

/* ---- Peripheral handles (generated by CubeMX) ---- */
extern SPI_HandleTypeDef  hspi2;
extern UART_HandleTypeDef huart2;

/* ---- LoRa handle ---- */
static LoRa_HandleTypeDef lora = {
    .hspi      = &hspi2,
    .nss_port  = GPIOB, .nss_pin  = GPIO_PIN_12,
    .rst_port  = GPIOC, .rst_pin  = GPIO_PIN_6,
    .dio0_port = GPIOC, .dio0_pin = GPIO_PIN_7,
};

/* ---- RF Parameters (must match sensor node) ---- */
#define LORA_FREQ       433000000UL
#define LORA_SF         7
#define LORA_BW         125000UL
#define LORA_CR         5
#define LORA_TX_POWER   17            // 17 dB out of 24 dB
#define LORA_SYNC_WORD  0x34

#define PKT_LEN         10

/* ---- retarget printf → UART2 ---- */
int __io_putchar(int ch) {
    HAL_UART_Transmit(&huart2, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ---- CRC-8 (must match sender) ---- */
static uint8_t crc8(const uint8_t *data, uint8_t len) {
    uint8_t crc = 0x00;
    for (uint8_t i = 0; i < len; i++) {
        uint8_t byte = data[i];
        for (uint8_t b = 0; b < 8; b++) {
            if ((crc ^ byte) & 0x80) crc = (crc << 1) ^ 0x31;
            else                      crc = (crc << 1);
            byte <<= 1;
        }
    }
    return crc;
}

/* ---- Decoded sensor data ---- */
typedef struct {
    uint8_t  node_id;
    uint16_t seq;
    float    temp_c;
    float    hum_pct;
    uint16_t vbat_mv;
    int8_t   rssi;
    int8_t   snr;
} SensorFrame;

static bool parse_packet(const uint8_t *buf, uint8_t len, SensorFrame *f) {
    if (len < PKT_LEN) return false;

    uint8_t crc_rx  = buf[9];
    uint8_t crc_calc = crc8(buf, 9);
    if (crc_rx != crc_calc) return false;

    f->node_id  = buf[0];
    f->seq      = ((uint16_t)buf[1] << 8) | buf[2];
    int16_t t10 = ((int16_t)buf[3] << 8) | buf[4];
    uint16_t h10= ((uint16_t)buf[5] << 8) | buf[6];
    f->temp_c   = t10  / 10.0f;
    f->hum_pct  = h10  / 10.0f;
    f->vbat_mv  = ((uint16_t)buf[7] << 8) | buf[8];
    return true;
}

/* ---- Application entry (called from main() after HAL/clock init) ---- */
void Gateway_Run(void) {
    printf("\r\n=============================\r\n");
    printf("  LoRa Gateway | STM32L476RG \r\n");
    printf("=============================\r\n");

    if (!LoRa_Init(&lora, LORA_FREQ, LORA_SF, LORA_BW,
                   LORA_CR, LORA_TX_POWER, LORA_SYNC_WORD)) {
        printf("[ERROR] LoRa SX1278 init failed! Check wiring.\r\n");
        Error_Handler();
    }
    printf("[OK] LoRa init  freq=%luMHz  SF=%u  BW=%lukHz\r\n",
           LORA_FREQ / 1000000UL, LORA_SF, LORA_BW / 1000UL);

    LoRa_StartReceive(&lora);
    printf("[LISTEN] Waiting for sensor packets...\r\n\r\n");

    uint8_t     buf[64];
    SensorFrame frame;
    uint32_t    pkt_count = 0;
    uint32_t    crc_errors = 0;

    while (1) {
        /* Poll DIO0 / IRQ register */
        if (LoRa_PacketAvailable(&lora)) {
            int8_t rssi, snr;
            int    len = LoRa_Receive(&lora, buf, sizeof(buf), &rssi, &snr);

            if (len == -2) {
                crc_errors++;
                printf("[CRC ERR] HW CRC error #%lu\r\n", crc_errors);
            } else if (len > 0) {
                frame.rssi = rssi;
                frame.snr  = snr;

                if (parse_packet(buf, (uint8_t)len, &frame)) {
                    pkt_count++;
                    printf("--[ PKT #%lu ]--\r\n", pkt_count);
                    printf("  Node   : 0x%02X\r\n",  frame.node_id);
                    printf("  Seq    : %u\r\n",       frame.seq);
                    printf("  Temp   : %.1f C\r\n",   frame.temp_c);
                    printf("  Hum    : %.1f %%\r\n",  frame.hum_pct);
                    printf("  VBat   : %u mV\r\n",    frame.vbat_mv);
                    printf("  RSSI   : %d dBm\r\n",   frame.rssi);
                    printf("  SNR    : %d dB\r\n\r\n",frame.snr);
                } else {
                    crc_errors++;
                    printf("[WARN] Soft CRC mismatch  raw_len=%d\r\n", len);
                }
            }

            /* Re-arm receiver */
            LoRa_StartReceive(&lora);
        }

        HAL_Delay(1);   // Yield; replace with RTOS vTaskDelay if needed
    }
}
